# Generated by Django 4.2 on 2026-05-21 00:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_protocols', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledHealthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_health_events', to='animals.animal')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='health.healthprotocol')),
            ],
        ),
        migrations.AddField(
            model_name='healthprotocol',
            name='treatments',
            field=models.ManyToManyField(blank=True, to='health.treatment'),
        ),
        migrations.AddField(
            model_name='healthprotocol',
            name='vaccines',
            field=models.ManyToManyField(blank=True, to='health.vaccine'),
        ),
    ]
