# Generated by Django 4.2 on 2026-05-21 00:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'unique_together': {('farm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LotMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_memberships', to='animals.animal')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='lots.lot')),
            ],
            options={
                'verbose_name': 'Lot Membership',
                'verbose_name_plural': 'Lot Memberships',
                'unique_together': {('lot', 'animal')},
            },
        ),
    ]
