# Generated by Django 4.2 on 2026-05-21 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BIRTH', 'Birth'), ('MOVEMENT', 'Movement'), ('VACCINATION', 'Vaccination'), ('TREATMENT', 'Treatment'), ('SERVICE', 'Service'), ('CALVING', 'Calving'), ('WEANING', 'Weaning'), ('WEIGHING', 'Weighing'), ('DEATH', 'Death'), ('SALE', 'Sale'), ('COUNT', 'Count'), ('MISSING', 'Missing')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='animals.animal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
