# Generated by Django 4.2 on 2026-05-21 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rfid_service_uuid', models.CharField(blank=True, help_text='The Bluetooth Service UUID of the RFID reader.', max_length=36, null=True)),
                ('rfid_characteristic_uuid', models.CharField(blank=True, help_text='The Bluetooth Characteristic UUID for RFID notifications.', max_length=36, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('READONLY', 'Readonly')], default='OPERATOR', max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['farm__name', 'user__username'],
                'unique_together': {('user', 'farm')},
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='members',
            field=models.ManyToManyField(related_name='farms', through='farms.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
