# Generated by Django 4.2 on 2026-05-21 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('locations', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='locations.location')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='farms.farm')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='locations.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movement',
                'verbose_name_plural': 'Movements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MovementAnimal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_history', to='animals.animal')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals_involved', to='movements.movement')),
            ],
            options={
                'verbose_name': 'Movement Animal',
                'verbose_name_plural': 'Movement Animals',
                'unique_together': {('movement', 'animal')},
            },
        ),
    ]
