# Generated by Django 4.2 on 2026-05-21 00:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measurement_date', models.DateTimeField()),
                ('scale_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Weight Measurement',
                'verbose_name_plural': 'Weight Measurements',
                'ordering': ['-measurement_date'],
            },
        ),
    ]
