# Generated by Django 4.2 on 2026-05-21 00:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('paddock', 'Paddock'), ('corral', 'Corral'), ('pen', 'Pen'), ('temporary_plot', 'Temporary Plot'), ('custom', 'Custom')], default='paddock', max_length=20)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('manual_area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculated_area_hectares', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'unique_together': {('farm', 'name')},
            },
        ),
    ]
